blank_issues_enabled: false
contact_links:
  - name: Bug report
    url: https://github.com/nikitabobko/AeroSpace/discussions/categories/potential-bugs
    about: 'All bug reports must firstly go to #potential-bugs GH discussion'
  - name: Feature request/idea
    url: https://github.com/nikitabobko/AeroSpace/discussions/categories/feature-ideas
    about: 'All feature requests must be firstly discussed in #feature-ideas GH discussion'
  - name: Ask a question
    url: https://github.com/nikitabobko/AeroSpace/discussions/categories/questions-and-answers
    about: 'Please ask and answer questions here'
